Repository sparta-USD/UNFT-front, pull requests merged in 2022-11, with the labels that each got.

#3 Feat : 회원가입, 로그인, 비밀번호 재설정, 비밀번호 찾기 html 화면 생성 #1
  find_pw.html
  set_pw.html
  signin.html
  signup.html
  static/css/signin.css
  static/css/signup.css
Labels: enhancement

#4 Feat: 메인화면 UI 및 U-nft 전체목록 API 연결
  index.html
  static/css/style.css
  static/js/mainAPI.js
Labels: enhancement

#7 Feat : 회원가입 페이지 API #5
  index.html
  signup.html
  static/css/style.css
  static/js/mainAPI.js
  static/js/signup.js
Labels: enhancement

#9 Feat : 로그인, 로그아웃 API 연결
  signin.html
  signup.html
  static/js/logout.js
  static/js/signin.js
Labels: enhancement

#12 Feat: 상세페이지 화면 UI 및 U-nft 상세목록 API 연결
  index.html
  static/css/detail.css
  static/css/style.css
  static/images/default_profile.png
  static/js/detailAPI.js
  static/js/mainAPI.js
  unft.html
Labels: enhancement

#10 Feat : 회원가입, 로그인, 로그아웃 API 연결
  find_pw.html
  set_pw.html
  signin.html
  signup.html
  static/css/signin.css
  static/css/signup.css
  static/js/logout.js
  static/js/signin.js
  static/js/signup.js
Labels: enhancement

#18 Design : UNFT 생성하기 html/css
  create_unft.html
  static/css/create_unft.css
  static/js/create_unft.js
Labels: enhancement

#15 Fix : 회원가입 시 체크박스 필수 체크해야만 회원가입 성공 #14
  signup.html
  static/css/signin.css
  static/css/signup.css
  static/js/signup.js
Labels: bug, enhancement

#17 Feat: 상세페이지에서 unft 상세조회API에 쿠키로 조회수 구현
  static/js/detailAPI.js
Labels: enhancement

#20 Feat: 프로필 페이지 UI 생성 #16
  profile.html
  static/css/profile.css
  static/js/main.js
  static/js/profile.js
Labels: enhancement

#21 Feat: U-NTF(작품) 생성 페이지 UI 작성 및 API 연결 #11
  create_unft.html
  static/css/create_unft.css
  static/js/create_unft.js
Labels: enhancement

#22 Feat: U-NFT 수정 페이지 UI 및 unft 수정 API 연결
  edit_unft.html
  static/css/create_unft.css
  static/js/edit_unft_api.js
Labels: enhancement

#23 Fix: mainAPI.js, detailAPi.js 이미지 경로 / 두개 수정, 회원가입 링크 수정 및 비밀번호찾기 링크 수정
  signin.html
  static/js/detailAPI.js
  static/js/mainAPI.js
Labels: bug

#28 Bug: 회원가입, 로그인 시 발생한 오류 체크 후 수정 #26
  signin.html
  signup.html
  static/css/signup.css
  static/js/create_unft.js
  static/js/signin.js
  static/js/signup.js
Labels: bug

#31 Feat: Navbar 링크 연결 및 로그인/로그아웃에 따른 메뉴 변화 구현 #30
  create_unft.html
  edit_unft.html
  find_pw.html
  index.html
  profile.html
  set_pw.html
  signin.html
  signup.html
  static/js/logout.js
  unft.html
Labels: enhancement

#29 Feat: U-NFT 상세 - 거래내역 및 최근 제안내역 API 연결 #27
  static/js/detailAPI.js
  unft.html
Labels: enhancement

#32 Feat: create_unft.html 전체적으로 확인하기 #24
  static/js/create_unft.js
Labels: enhancement

#34 Feat: 프로필페이지에 내새끼/내가만든작품/거래내역/제안내역 API 연결
  profile.html
  static/css/profile.css
  static/js/main.js
  static/js/mainAPI.js
  static/js/profile.js
Labels: enhancement

#35 Feat: unft 생성페이지에 loader 구현
  create_unft.html
  static/css/style.css
  static/js/create_unft.js
Labels: enhancement

#36 Feat: create_unft.html 기능 추가 및 css 수정 #24
  create_unft.html
  static/js/create_unft.js
Labels: enhancement

#37 Feat: U-NFT 상세페이지 - 제안하기 모달 기능 #33
  static/css/detail.css
  static/js/detailAPI.js
  unft.html
Labels: enhancement

#40 Feat: 메인 베너이미지 변경 #39
  index.html
  static/images/unft.png
Labels: enhancement

#42 Feat: UNFT 상세페이지 UI 수정 #41
  static/js/detailAPI.js
  unft.html
Labels: enhancement

#45 Feat: 로그인시 회원정보 로컬스토리지에 저장해서 페이지 권한 관리하기
  static/js/detailAPI.js
  static/js/logout.js
  static/js/signin.js
  unft.html
Labels: bug, enhancement

#47 Bug: U-NFT 생성 페이지 에러 수정
  create_unft.html
  static/js/create_unft.js
Labels: bug

#48 Bug: 프로필페이지 unft수정, 삭제 API #38
  profile.html
  static/js/edit_unft_api.js
  static/js/profile.js
Labels: bug

#49 Feat: 프로필페이지 [수정]버튼, [삭제]버튼 생성및 API 연결
  profile.html
  static/js/profile.js
Labels: enhancement

#51 Feat: 내가 받은 제안내역 승인/거절 API연결 #50
  static/js/profile.js
Labels: enhancement
